dbstat_project/assets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

dbstat_project/dbstat_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from contacts import views as contact_views
from dbstat_site import views as homepage_views

urlpatterns = [
    path('', homepage_views.index, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('assets/', include('assets.urls')),
    path('locations/', include('locations.urls')),
    path('profile/', contact_views.profile, name='profile'),
    path('register/', contact_views.register, name='register'),
    path('tickets/', include('tickets.urls'))
]

dbstat_project/locations/urls.py
from django.urls import path

from . import views

app_name = 'locations'
urlpatterns = [
    path('', views.LocationListView.as_view(), name='locations-home'),
    path('new/', views.LocationCreateView.as_view(), name='locations-create'),
    path('<int:pk>/', views.LocationDetailView.as_view(), name='locations-detail'),
    path('<int:pk>/update', views.LocationUpdateView.as_view(), name='locations-update'),
]

dbstat_project/tickets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

dbstat_project/assets/models.py
from django.db import models

# Create your models here.

dbstat_project/contacts/models.py
from django.db import models

# Create your models here.

dbstat_project/locations/models.py
from address.models import AddressField
from datetime import date
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

class locations(models.Model):
    name = models.CharField(max_length=30, unique=True)
    address = AddressField(blank=True, null=True)
    phone_number = PhoneNumberField(unique=True, blank=True, null=True)
    website = models.CharField(max_length=255, blank=True, null=True)
    opened = models.DateField(auto_now=False, blank=True, null=True)
    sqft = models.PositiveIntegerField(blank=True, null=True)
    number_cages = models.PositiveIntegerField(blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('locations:locations-detail', kwargs={'pk': self.pk})

class positions(models.Model):
    title = models.CharField(max_length=30, unique=True)
    
    def __str__(self):
        return self.title
    
class staff(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = PhoneNumberField(unique=True)
    email = models.EmailField(max_length=255, unique=True)
    position_id = models.ForeignKey(positions, on_delete=models.RESTRICT)
    
class location_staff(models.Model):
    location_id = models.ForeignKey(locations, on_delete=models.RESTRICT)
    staff_id = models.ForeignKey(staff, on_delete=models.RESTRICT)
    position_id = models.ForeignKey(positions, on_delete=models.RESTRICT)

dbstat_project/tickets/models.py
from django.db import models

# Create your models here.

dbstat_project/contacts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email']

dbstat_project/locations/forms.py
from django.forms import ModelForm
from address.forms import AddressField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Column, Row, Submit

from .models import locations

class LocationForm(ModelForm):
    address = AddressField()
    class Meta:
        model = locations
        fields = [
            'name', 
            'address', 
            'phone_number', 
            'website'
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'LocationForm'
        self.helper.form_method = 'post'
        self.helper.form_action = 'create_location'
        self.helper.add_input(Submit('submit', 'Create'))
        self.helper.layout = Layout (
            Row(
                Column('name', css_class='form-group col-md-6 mb-0'),
                Column('phone_number', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            'address',
            'website'
        )

dbstat_project/assets/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, 'assets/index.html')

dbstat_project/contacts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .forms import UserRegistrationForm, UserUpdateForm

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render (request, 'contacts/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
    context = {
        'u_form': u_form
    }
    
    return render(request, 'contacts/profile.html', context)

dbstat_project/dbstat_site/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'base/index.html')

dbstat_project/locations/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import generic

from .forms import LocationForm
from .models import locations

class LocationListView(LoginRequiredMixin, generic.ListView):
    model = locations
    context_object_name = 'locations'
    ordering = ['name']

class LocationDetailView(LoginRequiredMixin, generic.DetailView):
    model = locations
    context_object_name = 'location'

class LocationCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'locations/locations_form.html'
    form_class = LocationForm
    
class LocationUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = locations
    context_object_name = 'location'
    fields = ['name', 'address', 'phone_number', 'website', 'opened']

dbstat_project/tickets/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, 'tickets/index.html')

dbstat_project/assets/templates/assets/index.html
{% extends "base/navbase.html" %}

{% block content %}
{% load static %}
<h1>Assets Home Page!</h1>
{% endblock %}

dbstat_project/contacts/templates/contacts/login.html
{% extends "base/loginbase.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

dbstat_project/contacts/templates/contacts/logout.html
{% extends "base/loginbase.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            Log In Again? <a href="{% url 'register' %}">Sign In</a>
        </small>
    </div>
{% endblock content %}

dbstat_project/contacts/templates/contacts/profile.html
{% extends "base/navbase.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

dbstat_project/contacts/templates/contacts/register.html
{% extends "base/navbase.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have an Account? <a class="ml-2" href="{% url 'register' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

dbstat_project/dbstat_site/templates/base/index.html
{% extends "base/navbase.html" %}

{% block content %}
{% load static %}
<div id="hero-image"></div>
{% endblock content %}

dbstat_project/dbstat_site/templates/base/loginbase.html
{% extends "base/skeleton.html" %}
{% load static %}
<!doctype html>
{% block body %}
  <body class="login">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock content %}
{% endblock body %}

dbstat_project/dbstat_site/templates/base/navbase.html
{% extends "base/skeleton.html" %}
{% load static %}
    {% block body %}
    <body>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand" href="{% url 'homepage' %}">
            <img src="{% static 'images/dbstatlogo.png' %}" width="282" height="61" class="d-inline-block align-center" alt="" loading="lazy">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarexpander" aria-controls="navbarexpander" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarexpander">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarLocations" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Locations
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarLocations">
                  <a class="dropdown-item" href="{% url 'locations:locations-create' %}">New Location</a>
                  <a class="dropdown-item" href="{% url 'locations:locations-home' %}">Existing Locations</a>
                  <a class="dropdown-item" href="#">Under Construction</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarContacts" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Contacts
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarContacts">
                  <a class="dropdown-item" href="#">Add Contact</a>
                  <a class="dropdown-item" href="#">Search Contacts</a>
                  <a class="dropdown-item" href="#">Contact Administration</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarAssets" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Assets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarAssets">
                  <a class="dropdown-item" href="#">New Assets</a>
                  <a class="dropdown-item" href="#">Unassigned Assets</a>
                  <a class="dropdown-item" href="#">Existing Assets</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarTickets" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Tickets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarTickets">
                  <a class="dropdown-item" href="#">Submit Ticket</a>
                  <a class="dropdown-item" href="#">Pending Tickets</a>
                  <a class="dropdown-item" href="#">Closed Tickets</a>
                </div>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Welcome, {% if user.first_name %} {{ user.first_name }} {% else %} {{ user.username }} {% endif %}!
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarUser">
                  {% if request.user.is_staff %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Administration</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'profile' %}">Edit Profile</a>
                  <a class="dropdown-item" href="#exampleModalCenter" data-toggle="modal" data-target="#exampleModalCenter">Log Out</a>
                </div>
                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        Are you sure you want to log out?
                      </div>
                      <div class="modal-footer">
                        <form method="post" action="{% url 'account_logout' %}">
                          {% csrf_token %}
                          {% if redirect_field_value %}
                          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                          {% endif %}
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                          <button type="submit" class="btn btn-danger">Yes</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </header>
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
      {% endblock body %}
      </main>
    

dbstat_project/dbstat_site/templates/base/skeleton.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Raleway&family=Roboto:wght@500&family=Volkhov:ital,wght@1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% block title %}<title>D-BAT STAT</title>{% endblock %}
  </head>
    {% block body %}
    {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
  </body>
</html>

dbstat_project/locations/templates/locations/locations_detail.html
{% extends "base/navbase.html" %}

{% block content %}
    <h1>{{ location.name }}</h1>
    <p>{{ location.address }}</p>
{% endblock content %}

dbstat_project/locations/templates/locations/locations_form.html
{% extends "base/navbase.html" %}
{% load crispy_forms_tags %}
{{ form.media }}
{% block content %}
{% crispy form %}
{% endblock content %}

dbstat_project/locations/templates/locations/locations_list.html
{% extends "base/navbase.html" %}

{% block content %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% for location in locations %}
                    <ul>
                        <li><a href="{% url 'locations:locations-detail' location.id %}">{{ location.name }}</a></li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock content %}

dbstat_project/tickets/templates/tickets/index.html
{% extends "base/navbase.html" %}

{% block content %}
{% load static %}
<h1>Tickets Home Page!</h1>
{% endblock %}